# Generated by Django 2.0.2 on 2018-04-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0004_auto_20180315_2014'),
    ]

    operations = [
    ]
