# Generated by Django 2.0.2 on 2018-05-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0009_auto_20180408_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarperiod',
            options={'ordering': ['calendar_period_id'], 'permissions': {('view_calendarperiod', 'Can view calendar period')}},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_number'], 'permissions': {('view_course', 'Can view course')}},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['last_name', 'first_name'], 'permissions': {('view_instructor', 'Can view instructor')}},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['course__course_number', 'section_name', 'semester'], 'permissions': {('view_section', 'Can view section')}},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year', 'calendar_period__calendar_period_id'], 'permissions': {('view_semester', 'Can view semester')}},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'permissions': {('view_student', 'Can view student')}},
        ),
        migrations.AlterField(
            model_name='semester',
            name='calendar_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='courseinfo.CalendarPeriod'),
        ),
    ]
